# Generated by Django 2.1.7 on 2019-03-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelformsApp', '0002_auto_20190325_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='Trainee', max_length=50),
        ),
    ]
