# Generated by Django 2.1.7 on 2019-03-13 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('designation', models.CharField(choices=[('CEO', 'CEO'), ('Senior Software Engineer', 'Senior Software Engineer'), ('Project Manager', 'Project Manager'), ('Trainee', 'Trainee')], max_length=50)),
                ('reporting_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelApp.Employee')),
            ],
        ),
    ]
