# Generated by Django 2.1.7 on 2019-03-15 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='modelApp.Employee'),
        ),
    ]
